### ISSUE TITLE
Package command

### ISSUE THREAD

**Issue by josteph** [Kiyozz/electron-esbuild#16]
Hi, thanks for the great esbuild & electron scaffolding.

Is there any additional setup needed in order to run the `package` command?
I tried running the package command, and here's the error:

```
> josteph-electron-esbuild@1.0.0 package /Users/joshua/Documents/GitHub/josteph-electron-esbuild
> electron-builder

  • electron-builder  version=22.10.5 os=20.3.0
  • loaded configuration  file=package.json ("build" field)
  ⨯ Cannot find package.json in the /Users/joshua/Documents/GitHub/josteph-electron-esbuild/src  stackTrace=
                                                                                                   Error: Cannot find package.json in the /Users/joshua/Documents/GitHub/josteph-electron-esbuild/src
                                                                                                       at Packager.readProjectMetadataIfTwoPackageStructureOrPrepacked (/Users/joshua/Documents/GitHub/josteph-electron-esbuild/node_modules/.pnpm/registry.npmjs.org/app-builder-lib/22.10.5/node_modules/app-builder-lib/src/packager.ts:403:11)
                                                                                                       at Packager.build (/Users/joshua/Documents/GitHub/josteph-electron-esbuild/node_modules/.pnpm/registry.npmjs.org/app-builder-lib/22.10.5/node_modules/app-builder-lib/src/packager.ts:324:24)
                                                                                                       at executeFinally (/Users/joshua/Documents/GitHub/josteph-electron-esbuild/node_modules/.pnpm/registry.npmjs.org/builder-util/22.10.5/node_modules/builder-util/src/promise.ts:12:14)
 ERROR  Command failed with exit code 1.
```

So it expects `package.json` needs to be present in `src` folder.
Is it what it should be? Or maybe did I miss something during the setup process?

Context:
**Template**: react-ts
**Repo Link**: https://github.com/josteph/josteph-electron-esbuild

Thank you.

**Comment by Kiyozz** [comment]
Hey!

I see "directories" section in "build" in package.json

The app directory is setup up as "src", try to remove it

**Comment by josteph** [comment]
Hey, thanks for the quick reply.

Yes apparently it's a mistake on my end, thanks for pointing it out!
