### ISSUE TITLE
webpack-dev-server v4.*.* not supportd 

### ISSUE THREAD

**Issue by muhad-bk** [Kiyozz/electron-esbuild#28]
"webpack-dev-server": "^4.2.1" - 

> electron-esbuild dev

(node:33316) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
(Use `node --trace-deprecation ...` to show where the warning was created)
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'overlay'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, setupExitSignals?, static?, watchFiles?, webSocketServer? }
    at validate (D:\Projects\AflexGate\AflexGateWebpack\node_modules\.pnpm\schema-utils@3.1.1\node_modules\schema-utils\dist\validate.js:105:11)
    at new Server (D:\Projects\AflexGate\AflexGateWebpack\node_modules\.pnpm\webpack-dev-server@4.2.1_webpack@5.52.1\node_modules\webpack-dev-server\lib\Server.js:31:5)
    at k.dev (D:\Projects\AflexGate\AflexGateWebpack\node_modules\.pnpm\electron-esbuild@2.0.0_c9ab706cdaeb9f1f381984fdaecdbfee\node_modules\electron-esbuild\dist\builder\webpack.js:1:1552)
    at E.init (D:\Projects\AflexGate\AflexGateWebpack\node_modules\.pnpm\electron-esbuild@2.0.0_c9ab706cdaeb9f1f381984fdaecdbfee\node_modules\electron-esbuild\dist\commands\dev.js:1:2424)
    at Object.<anonymous> (D:\Projects\AflexGate\AflexGateWebpack\node_modules\.pnpm\electron-esbuild@2.0.0_c9ab706cdaeb9f1f381984fdaecdbfee\node_modules\electron-esbuild\dist\index.js:13:230)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
[000.00] (Commands/Dev) Exiting...
[000.00] (Commands/Dev) Killing main process...
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Kiyozz** [comment]
Hey, I'll look into it! Thanks!

**Comment by Kiyozz** [comment]
The new version should fix this ! This is a Breaking change, so next version will be 3.0.0 !

**Comment by Kiyozz** [comment]
Version 3.0.0 of electron-esbuild has been released
