### ISSUE TITLE
Source map not working for main process

### ISSUE THREAD

**Issue by beorn** [Kiyozz/electron-esbuild#36]
When I create an app using `yarn create @electron-esbuild/app` using the `main-ts` or `react-vite-ts` templates, and I make `main.ts` throw an exception (e.g., add a `throw Error('test')` at the bottom), the stack trace does not use a source map:

```log
[...]
App threw an error during load
Error: main
    at Object.<anonymous> (.../myapp/dist/main/main.js:489:7)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (.../myapp/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (.../exp/myapp/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:222:9)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
```

But I can see that the source map is generated:

```console
% ls -al dist/main 
total 88
drwxr-xr-x  6 user  staff    192 Jan  8 11:35 .
drwxr-xr-x  3 user  staff     96 Jan  8 11:31 ..
-rw-r--r--  1 user  staff  16311 Jan  8 11:36 main.js
-rw-r--r--  1 user  staff  20472 Jan  8 11:36 main.js.map
-rw-r--r--  1 user  staff     93 Jan  8 11:36 preload.js
-rw-r--r--  1 user  staff    170 Jan  8 11:36 preload.js.map
```

Adding `sourcemap: true` to `tsconfig.json` and `esbuild.main.config.ts` did not help.

[Node 12 added a `--enable-source-maps`](https://nodejs.org/dist/latest-v16.x/docs/api/cli.html#--enable-source-maps) - and this may become the default nodejs/node#38817

Not sure how to enable that for the node in Electron?

**Comment by Kiyozz** [comment]
I think you need to install "source-map-support" package.

Install it as dev: when using electron-esbuild, install all packages as dev.

Only packages with binaries must be installed as prod, and added as external.

Finally, use it in the main process (follow the doc).

**Comment by beorn** [comment]
I'm able to get source maps working by setting `NODE_OPTIONS="--enable-source-maps"`, but not by passing the `--js-flags=--enable-source-maps` command line option to electron [in the dev command](https://github.com/Kiyozz/electron-esbuild/blob/34f142a47dd4e3fd4a6cf3f7c6760b0e6be98d20/packages/electron-esbuild/src/commands/dev.mts#L47).

The node option is a newer way that using the source-map-support package.

**Comment by Kiyozz** [comment]
I'll need to pass through unknown electron-esbuild's options to electron so the js-flags to work

**Comment by Kiyozz** [comment]
#40 will handle additional arguments to be passed to the electron process. The readme should be enough to understand how it works.

**Comment by i-am-the-slime** [comment]
Pretty nice of you to forfeit your 2021 copyright 😁
