### ISSUE TITLE
Bug: dev mode in esbuild 18 crash

### ISSUE THREAD

**Issue by himself65** [Kiyozz/electron-esbuild#55]
```shell
[000.00] (Builder/Esbuild) Building main
✘ [ERROR] Invalid option in build() call: "incremental"

    /Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:255:12:
      255 │       throw new Error(`Invalid option ${where}: ${quote(key)}`);
          ╵             ^

    at checkForInvalidFlags (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:255:13)
    at flagsForBuildOptions (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:463:3)
    at buildOrContextContinue (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:1012:9)
    at buildOrContextImpl (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:996:5)
    at Object.buildOrContext (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:779:5)
    at /Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:2166:15
    at new Promise (<anonymous>)
    at Object.build (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:2165:25)
    at Object.build (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:2014:51)
    at EsbuildBuilder.build (file:///Users/himself65/Code/AFFiNE/apps/electron/node_modules/electron-esbuild/dist/builder/esbuild.builder.mjs:26:37)

Error: Build failed with 1 error:
/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:255:12: ERROR: Invalid option in build() call: "incremental"
    at failureErrorWithLog (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:1639:15)
    at /Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:956:16
    at responseCallbacks.<computed> (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:700:9)
    at handleIncomingPacket (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:755:9)
    at Socket.readFromStdout (/Users/himself65/Code/AFFiNE/apps/electron/node_modules/esbuild/lib/main.js:676:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

Process finished with exit code 1
```

**Comment by Kiyozz** [comment]
Seems related to #51
Which is fixed in latest version.

Provide the version you're using or upgrade yours.

Update: It seems I did not update on npm. I will need to publish it, but I can't right now.

**Comment by Kiyozz** [comment]
electron-esbuild@8.0.0 is available which contains the fixes
